// Schema for Healthcare Context Graph
// Generated by create-context-graph

// Auto-generated schema for domain: Healthcare
// Generated by create-context-graph

CREATE INDEX person_name IF NOT EXISTS FOR (n:Person) ON (n.name);

CREATE INDEX organization_name IF NOT EXISTS FOR (n:Organization) ON (n.name);

CREATE INDEX location_name IF NOT EXISTS FOR (n:Location) ON (n.name);

CREATE INDEX event_name IF NOT EXISTS FOR (n:Event) ON (n.name);

CREATE INDEX object_name IF NOT EXISTS FOR (n:Object) ON (n.name);

CREATE CONSTRAINT patient_patient_id_unique IF NOT EXISTS FOR (n:Patient) REQUIRE n.patient_id IS UNIQUE;
CREATE INDEX patient_name IF NOT EXISTS FOR (n:Patient) ON (n.name);

CREATE CONSTRAINT provider_provider_id_unique IF NOT EXISTS FOR (n:Provider) REQUIRE n.provider_id IS UNIQUE;
CREATE INDEX provider_name IF NOT EXISTS FOR (n:Provider) ON (n.name);

CREATE CONSTRAINT diagnosis_icd_code_unique IF NOT EXISTS FOR (n:Diagnosis) REQUIRE n.icd_code IS UNIQUE;
CREATE INDEX diagnosis_name IF NOT EXISTS FOR (n:Diagnosis) ON (n.name);

CREATE CONSTRAINT treatment_treatment_id_unique IF NOT EXISTS FOR (n:Treatment) REQUIRE n.treatment_id IS UNIQUE;
CREATE INDEX treatment_name IF NOT EXISTS FOR (n:Treatment) ON (n.name);

CREATE CONSTRAINT encounter_encounter_id_unique IF NOT EXISTS FOR (n:Encounter) REQUIRE n.encounter_id IS UNIQUE;
CREATE INDEX encounter_name IF NOT EXISTS FOR (n:Encounter) ON (n.name);

CREATE CONSTRAINT facility_facility_id_unique IF NOT EXISTS FOR (n:Facility) REQUIRE n.facility_id IS UNIQUE;
CREATE INDEX facility_name IF NOT EXISTS FOR (n:Facility) ON (n.name);

CREATE CONSTRAINT medication_ndc_code_unique IF NOT EXISTS FOR (n:Medication) REQUIRE n.ndc_code IS UNIQUE;
CREATE INDEX medication_name IF NOT EXISTS FOR (n:Medication) ON (n.name);

// Infrastructure: Document and Decision Trace indexes
CREATE INDEX document_title IF NOT EXISTS FOR (n:Document) ON (n.title);
CREATE INDEX document_template_id IF NOT EXISTS FOR (n:Document) ON (n.template_id);
CREATE CONSTRAINT decision_trace_id_unique IF NOT EXISTS FOR (n:DecisionTrace) REQUIRE n.id IS UNIQUE;

// Local-file connector: Document + Section node constraints and indexes
CREATE CONSTRAINT document_name_unique IF NOT EXISTS FOR (n:Document) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT section_name_unique IF NOT EXISTS FOR (n:Section) REQUIRE n.name IS UNIQUE;

// Range indexes for pre-filtering on both node types
CREATE INDEX document_domain IF NOT EXISTS FOR (n:Document) ON (n.domain);
CREATE INDEX document_source_type IF NOT EXISTS FOR (n:Document) ON (n.sourceType);
CREATE INDEX document_file_extension IF NOT EXISTS FOR (n:Document) ON (n.fileExtension);
CREATE INDEX document_language IF NOT EXISTS FOR (n:Document) ON (n.language);
CREATE INDEX document_loaded_at IF NOT EXISTS FOR (n:Document) ON (n.loadedAt);
CREATE INDEX document_created_at IF NOT EXISTS FOR (n:Document) ON (n.createdAt);
CREATE INDEX document_modified_at IF NOT EXISTS FOR (n:Document) ON (n.modifiedAt);
CREATE INDEX document_file_size IF NOT EXISTS FOR (n:Document) ON (n.fileSize);
CREATE INDEX document_page_count IF NOT EXISTS FOR (n:Document) ON (n.pageCount);
CREATE INDEX section_domain IF NOT EXISTS FOR (n:Section) ON (n.domain);
CREATE INDEX section_file_extension IF NOT EXISTS FOR (n:Section) ON (n.fileExtension);
CREATE INDEX section_heading_level IF NOT EXISTS FOR (n:Section) ON (n.headingLevel);
CREATE INDEX section_loaded_at IF NOT EXISTS FOR (n:Section) ON (n.loadedAt);

// Full-text index for keyword search over Document + Section titles and bodies
CREATE FULLTEXT INDEX local_file_fulltext IF NOT EXISTS FOR (n:Document|Section) ON EACH [n.title, n.description];

// Vector index for semantic search with pre-filtering (Neo4j 2026.01+)
// Create after embeddings are generated; dimensions must match your embed model.
// CREATE VECTOR INDEX local_file_embedding IF NOT EXISTS
// FOR (n:Document|Section) ON n.embedding
// WITH [n.domain, n.fileExtension, n.loadedAt, n.createdAt, n.modifiedAt,
//       n.fileSize, n.language, n.headingLevel, n.pageCount, n.author]
// OPTIONS { indexConfig: {
//   `vector.dimensions`: 1536, `vector.similarity_function`: 'cosine',
//   `vector.quantization.enabled`: true } };

