/**
 * Domain configuration for Healthcare
 * Generated by create-context-graph
 */

export const DOMAIN = {
  id: "healthcare",
  name: "Healthcare",
  description: "Patient care, clinical encounters, diagnoses, treatments, and provider networks",
  tagline: "AI-powered Clinical Intelligence",
};

export const API_BASE = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

export interface GraphData {
  results: Record<string, unknown>[];
}

export interface DemoScenario {
  name: string;
  prompts: string[];
}

export const DEMO_SCENARIOS: DemoScenario[] = [{"name": "Patient Lookup", "prompts": ["Show me all patients with a chronic diagnosis", "What medications are currently prescribed to patients in the cardiology department?", "Find all recent patient encounters in the last 6 months"]}, {"name": "Clinical Decision Support", "prompts": ["Are there any potential drug interactions in current prescriptions?", "What treatments have been most effective for patients with heart failure?"]}, {"name": "Provider Network", "prompts": ["Which providers are affiliated with the largest hospital in the network?", "Show the referral patterns between primary care and specialists", "Which providers have the most patient encounters this quarter?"]}];
